# Generated by Django 3.0.7 on 2020-06-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='actors/')),
                ('career', models.ManyToManyField(to='motion_pictures.Career')),
            ],
        ),
        migrations.CreateModel(
            name='MotionPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('imdb_id', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[(0, 'film'), (1, 'serial'), (2, 'anime'), (3, 'show')], max_length=200)),
                ('released', models.DateField()),
                ('iframe_src', models.CharField(max_length=200)),
                ('plot', models.TextField()),
                ('poster', models.CharField(max_length=300)),
                ('genre', models.ManyToManyField(to='motion_pictures.Genre')),
                ('languages', models.ManyToManyField(to='motion_pictures.Language')),
                ('memberships', models.ManyToManyField(to='motion_pictures.Membership')),
            ],
        ),
    ]
