# Generated by Django 3.0.7 on 2020-06-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion_pictures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotionPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.SlugField(max_length=200)),
                ('type', models.CharField(choices=[(0, 'film'), (1, 'serial'), (2, 'anime'), (3, 'show')], max_length=200)),
                ('released', models.DateField(blank=True, null=True)),
                ('iframe_src', models.CharField(max_length=200)),
                ('plot', models.TextField()),
                ('poster_url', models.CharField(blank=True, max_length=300, null=True)),
                ('genre', models.ManyToManyField(to='motion_pictures.Genre')),
                ('languages', models.ManyToManyField(to='motion_pictures.Language')),
                ('memberships', models.ManyToManyField(blank=True, null=True, to='motion_pictures.Membership')),
            ],
        ),
        migrations.DeleteModel(
            name='MotionPictures',
        ),
    ]
