# Generated by Django 3.0.7 on 2020-06-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion_pictures', '0002_auto_20200619_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motionpicture',
            name='memberships',
            field=models.ManyToManyField(blank=True, to='motion_pictures.Membership'),
        ),
    ]
