# Generated by Django 3.0.7 on 2020-06-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion_pictures', '0003_auto_20200619_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('name', models.ManyToManyField(to='motion_pictures.RatingName')),
            ],
        ),
        migrations.AddField(
            model_name='motionpicture',
            name='rating',
            field=models.ManyToManyField(to='motion_pictures.Rating'),
        ),
    ]
