# Generated by Django 3.0.7 on 2020-06-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion_pictures', '0004_auto_20200619_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motionpicture',
            name='genre',
        ),
        migrations.AddField(
            model_name='motionpicture',
            name='genres',
            field=models.ManyToManyField(related_name='genres', to='motion_pictures.Genre'),
        ),
        migrations.AlterField(
            model_name='motionpicture',
            name='languages',
            field=models.ManyToManyField(related_name='languages', to='motion_pictures.Language'),
        ),
        migrations.AlterField(
            model_name='motionpicture',
            name='memberships',
            field=models.ManyToManyField(blank=True, related_name='memmberships', to='motion_pictures.Membership'),
        ),
        migrations.AlterField(
            model_name='motionpicture',
            name='rating',
            field=models.ManyToManyField(related_name='ratings', to='motion_pictures.Rating'),
        ),
    ]
