# Generated by Django 3.0.7 on 2020-06-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion_pictures', '0005_auto_20200619_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motionpicture',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'film'), (1, 'serial'), (2, 'anime'), (3, 'show')]),
        ),
    ]
