# Generated by Django 3.0.7 on 2020-06-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion_pictures', '0006_auto_20200619_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motionpicture',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'movie'), (1, 'series'), (2, 'show')]),
        ),
    ]
