# Generated by Django 3.0.7 on 2020-06-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion_pictures', '0007_auto_20200619_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motionpicture',
            name='url',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
