# Generated by Django 3.0.7 on 2020-06-20 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motion_pictures', '0009_auto_20200620_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motionpicture',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motion_picture', to='motion_pictures.Rating'),
        ),
    ]
