# Generated by Django 3.0.7 on 2020-06-20 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motion_pictures', '0010_auto_20200620_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motionpicture',
            name='rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='motion_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motion_picture', to='motion_pictures.MotionPicture'),
        ),
    ]
