# Generated by Django 3.0.7 on 2020-06-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion_pictures', '0011_auto_20200620_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='max_value',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
