# Generated by Django 3.0.7 on 2020-06-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion_pictures', '0012_rating_max_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motionpicture',
            name='memberships',
            field=models.ManyToManyField(to='motion_pictures.Membership'),
        ),
    ]
