# Generated by Django 3.0.7 on 2020-06-20 21:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('motion_pictures', '0013_auto_20200620_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='motionpicture',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
