# Generated by Django 3.0.7 on 2020-06-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion_pictures', '0014_motionpicture_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motionpicture',
            name='genres',
            field=models.ManyToManyField(to='motion_pictures.Genre'),
        ),
        migrations.AlterField(
            model_name='motionpicture',
            name='languages',
            field=models.ManyToManyField(to='motion_pictures.Language'),
        ),
    ]
